# Simulating ADIS16448, a high-end IMU with the quote cost of $4300
# spec are collected from page 12 & 13 of datasheet:
# http://www.analog.com/media/en/technical-documentation/data-sheets/adis16448.pdf

fps: 200

noise_acc: 0.0022563    # [m/s^2/sqrt(Hz)] 
noise_gyr: 0.0002356    # [rad/s/sqrt(Hz)] 

noise_accbias: 8e-5     # [m/s^3/sqrt(Hz)]
noise_gyrbias: 3e-6     # [rad/s^2/sqrt(Hz)]