# Simulating BMI160, a low-end IMU with the quote cost of $6
# spec are collected from page 12 & 13 of datasheet:
# https://www.bosch-sensortec.com/bst/products/all_products/bmi160
# notice that the bias spec is not provided in data sheet, therefore 
# we can only guess it is 100-times worse than AIDS 16448

fps: 100

noise_acc: 0.001765    # [m/s^2/sqrt(Hz)] 
noise_gyr: 0.000140    # [rad/s/sqrt(Hz)] 

noise_accbias: 8e-3     # [m/s^3/sqrt(Hz)]
noise_gyrbias: 3e-4     # [rad/s^2/sqrt(Hz)]