# Simulating mpu6000, a low-end IMU with the quote cost of $5
# spec are collected from page 12 & 13 of datasheet:
# https://datasheet.octopart.com/MPU-6000-InvenSense-datasheet-14421344.pdf
#
# the random walk error is magnified by a factor of 10, 
# as suggested by Kalibr
# https://github.com/ethz-asl/kalibr/wiki/IMU-Noise-Model
#
# also note that the bias spec is not provided in data sheet, therefore 
# we can only guess it is 100-times worse than AIDS 16448

fps: 100

noise_acc: 0.03924    # [m/s^2/sqrt(Hz)] 
# noise_gyr: 0.00008726       # [rad/s/sqrt(Hz)] 
noise_gyr: 0.00276       # [rad/s/sqrt(Hz)] 

noise_accbias: 8e-3     # [m/s^3/sqrt(Hz)]
noise_gyrbias: 3e-4     # [rad/s^2/sqrt(Hz)]